connection:
  n1:
    ip: 10.245.74.71
    type: exa
    port: 22
    connect_timeout: 20
    protocol: ssh
    user: sysadmin
    password: sysadmin
    user_agent: CLI
    timeout: 10
    prompt: "#"
    ports:
      p1:
        port:  1/1/x4
      p2:
        port:  1/1/gp4
          
        

