global:
  service_model:
    # uplink eth port
    service_point_list1:
      - service_point1
    service_point1:
      device: eutA
      type: eth                  # service_point type {eth|lag|g8032|erps}
      member:
        interface1: CAFETOPO.connection.eutA.shelf1.slot1.uplinkport1
      attribute:
        interface_role: inni
        interface_type: ethernet

    subscriber_point1:
      device: eutA
      type: ont_port             # subscriber port type {ont_port|dsl|dsl_bond|eth}
      name: 801/x1
      member:
        interface1: 801/x1
      attribute:                 # all mandatory parameter should set to "" if you don't want to use it
        interface_role: uni
        interface_type: ont-ethernet
        ont_id: 801
        ont_profile_id: GP1000X     # use ont-profile on cli
        serial_number: 3D15BA
        vendor_id: CXNK
        pon_port:
          - CAFETOPO.connection.eutA.shelf1.slot1.downlinkport1


