connection:
  eutA:
    ip: 10.245.96.73
    user: sysadmin
    password: sysadmin
    type: AXOS
    model: MILAN
    protocol: ssh
    user_interface: CLI
    prompt: "#"
    timeout: 30
    shelf1:                                # new format to describe the shelves on the EUT.
      id: 1                                # new format to describe the shelf with shelf id on the EUT.
      slot1:                               # new format to describe the shelf with slot id on the EUT.
        id: 1                              # new format to describe the shelf with slot id on the EUT.
        model: ngpon                        # describe the card type.
#        uplinkport1: 1/1/x1                # new format to describe the uplink port.
        downlinkport1: 1/1/xp1              # new format to describe the downlink port.
  
