global:
  upgrade_server: 
  upgrade_usr: 
  upgrade_pwd: 
  directory_n: Negative_Test
  user1: adminr
  password1: adminr
  sys_server1: 10.245.249.151
  sys_server2: 
  sys_server3: 
  filename1: syslog_file1
  dummy_sys_server: 1.1.1.1
  default_hostname: 
  Default_Transport_Protocol: UDP
  Secure_Transport_Protocol: TCP
  Syslog_default_port: 514
  Default_Log_Level: WARN
  Default_Admin_State: ENABLED
  filename: syslog_file
  tacacs_server1: 
  tac_user: admin_tacacs
  tac_pwd: admintacacs
  tac_role: admin
  tac_secret: test_tacacs_server
  RadiusFileName: RadiusTCPDump
  RadiusFileName1: RadiusTCPDump1
  RadiusFileName2: RadiusTCPDump2
  operator_usr: operator
  operator_pwd: operator123
  calixsupport_usr: calixsupport
  tac_usr: tac
  # IP where ecrack application is running
  ecrack_ip: 10.1.0.8
  device_prompt: E3-16F
  # RADIUS TCs parameters
  syslog_dir: /var/log/syslog
  syslog_file: CAFETOPO.connection.n1_session1.ip
  secret: test_radius_server
  invalid_secret: test_radius_server1
  authentication: radius-then-local
  invalid_port: 1645
  default_port: 1812
  default_timeout: 3
  radius_timeout: 30
  invalid_timeout: xyz
  invalid_priority: xyz
  invalid_range_port: 65536
  invalid_range1_timeout: 0
  invalid_range_timeout: 31
  invalid_range_priority: 0
  invalid_range_retry: 11
  radius_admin_user: ar_ola
  radius_admin_password: ar
  radius_retry: 3
  radius_retry1: 10
  role: admin
  interface: craft1
  # Params for SNMP cases
  admin_state: enable
  trap_type: inform
  retries: 6
  timeout: 400
  security_level: authPriv
  user2: operr
  password2: operr
  oper_role: oper
syslog:
  severity_level:
    EMERG: 0
    ALERT: 1
    CRIT: 2
    ERR: 3
    WARN: 4
    NOTICE: 5
    INFO: 6
    DEBUG: 7
  facility_code:
    kern: 0
    user: 1
    mail: 2
    daemon: 3
    auth: 4
    syslog: 5
    lpr: 6
    news: 7
    uucp: 8
    authpriv: 10
    ftp: 11
    cron: 15
    local0: 16
    local1: 17
    local2: 18
    local3: 19
    local4: 20
    local5: 21
    local6: 22
    local7: 23
