connection:
    n1:
        ip: 10.245.96.71
        password: sysadmin
        user: sysadmin
        type: exa
        protocol: ssh
    n1_session1:
        ip: 10.245.96.71
        password: admin
        user: tac
        type: exa
        protocol: ssh
    n1_session2:
        ip: 10.245.96.71
        password: monitor
        user: monitor
        type: exa
        protocol: ssh
    n1_session3:
        ip: 10.245.96.71
        password: networkadmin
        user: networkadmin
        type: exa
        protocol: ssh
    n1_session4:
        ip: 10.245.96.71
        password: support
        user: support
        type: exa
        protocol: ssh
    n1_session5:
        ip: 10.245.96.71
        password: gulf3tre4mg6
        user: calixsupport
        type: exa
        protocol: ssh

    h1:
        ip: localhost
        type: linux
        protocol: ssh
        user: cafetest
        password: cafetest

  
