global:
  server_add: 10.245.243.130
  server_udp_port: 1
  packets: 10
  default_state1: not running
  default_state2: stop
  start_state: running
  default_capture_source: none
  p_check_switchover_status: 5min   
#  
#  tg_server:
#    mac: 00:00:00:67:00:01
#    ip: 10.1.67.100
#  tg_client: 
#    mac: 00:00:00:11:11:11
#    ip: 10.1.67.10
#  
#  pkt_rate: 10     # send packet rate, unit mbps
#  traffic_run_time: 10           # run traffic for 10s
#  stc_wait_time: 5
#  traffic_loss_rate: 0.001        # traffic loss rate  
#  tg_store_file_path: /tmp
  