connection:
  eutA:
    ip: 10.245.74.73
    user: sysadmin
    password: sysadmin
    type: AXOS
    model: MILAN
    protocol: ssh
    user_interface: CLI
    prompt: "#"
    timeout: 30
    shelf1:
      id: 1
      slot1:
        id: 1
        model: gpon8r2
        uplinkport1: 1/2/x3
        downlinkport1: 1/1/gp1

  tg1:
    ip: 10.245.252.60
    type: stc
    protocol: stc
    ports:
      service_p1:
        port: 10/9
        medium: copper
        speed: ether1000
      subscriber_p1:
        port: 10/10
        medium: copper
        speed: ether1000