global:
  #class map type
  tacacs_ip_1: 10.245.251.27
  tacacs_ip_domain:  nanE7-09.calix.local
  tacacs_ip_2: 10.245.251.2
  tacacs_ip_3: 10.245.251.3
  tacacs_ip_4: 10.245.251.4
  tacacs_ip_5: 10.245.251.5
  tacacs_ps: testing123
  g_class_map_type:
    - ethernet
    - ip

  g_flow_index:
    - 1
    - 2
    - 3

  policy_map_name:    pmap-at1
  class_map_name:    cmap_at1
  server_ip:
    - 192.168.33.10
  ntp_staus:
    - Operational
  remote_reference_id:
    - 172.23.41.10
    - Not Available

  connection_status:
    - Connected
    - Trying to connect

  synchronize_status:
    - Synchronized
    - Unsynchronized
  source_status:
    - Source selected, synchronized
    - Has not passed sanity












