connection:
  eutA:
    ip: 10.245.96.74
    user: sysadmin
    password: sysadmin
    type: AXOS
    model: MILAN
    protocol: ssh
    user_interface: CLI
    prompt: "#"
    timeout: 30
    shelf1:
      id: 1
      slot1:
        id: 2
        model: 10GE-12 
        uplinkport1: 1/2/x7  
        downlinkport1: 1/2/x8
