global:
  service_model:
    service_point_list1:
      - service_point1
    service_point1:
      device: eutA
      type: eth
      member:
        interface1: 1/1/x1
      attribute:
        interface_role: inni
