global:
  service_model:
    service_point_list1:
      - service_point1
    service_point1:
      device: eutA
      type: eth
      member:
        interface1: 1/1/x3
      attribute:
        interface_role: inni

    subscriber_point1:
      device: eutA
      type: ont_port             # subscriber port type {ont_port|dsl|dsl_bond|eth}
      name: 1/g1
      member:
        interface1: 1/g1
      attribute:                 # all mandatory parameter should set to "" if you don't want to use it
        interface_role: uni
        ont_id: 1
        ont_profile_id: 836GE_ARF     # use ont-profile on cli
        serial_number: 1325BB
        vendor_id: CXNK
        pon_port:       # use list for FFP
          - 1/1/gp1
          - 1/1/gp2
          - 1/1/gp3
          - 1/1/gp4
