global:
  service_vlan:  402

  proxy_server_hostname:  hostname
  proxy_server_secondary_ip:  10.245.252.4
  proxy_server_secondary_host:  secondhostname  
  proxy_server_secondary:  0.0.0.0
  proxy_server_secondary1:  0.0.0.1
  proxy_server_secondary2:  0.0.0.2
  proxy_server_port:  '5060'
  proxy_server_port_secondary:  '5060'
  proxy_server_port_secondary1:  '1'
  proxy_server_port_secondary2:  '65535'
  proxy_server_port_secondary3:  '0'
  proxy_server_port_secondary4:  '65536'
  dns_primary:  0.0.0.0 
  dns_primary_1:  0.0.0.1
  dns_primary_2:  0.0.0.2
  dns_secondary:  0.0.0.0
  dns_secondary_1:  0.1.0.1
  codec:  ulaw
  packet_rate1:  '10'
  packet_rate2:  '20'
  packet_rate3:  '30'
  sil_sup_def:  disabled
  sil_sup_modi:  enabled
  t1_timer:  '500'
  t1_timer_100:  '100'
  t1_timer_50:  '50'
  t1_timer_1500:  '1500'
  t1_timer_1501:  '1501'
  t2_timer:  '4'
  t2_timer_1:  '1'
  t2_timer_4:  '4'
  t2_timer_0:  '0'
  t2_timer_6:  '6'
  registration_period:  '3600'
  registration_period_59:  '59'
  registration_period_60:  '60'
  registration_period_86401:  '86401'
  registration_period_86400:  '86400'
  distinct_ring_prefix:  Bellcore-dr
  distinct_ring_prefix_ont:  Bellcore 
  distinct_ring_prefix_modi:  'abcdefghijklmnopqrst'
  distinct_ring_prefix_modi1:  'ABCdefghijklmnopqrst' 
  call_waiting_prefix:  CallWaitingTone
  call_waiting_prefix_modi:  'abcdefghijklmnopqrst'  
  out_of_band_dtmf:  none
  out_of_band_dtmf1:  rfc2833
  out_of_band_dtmf2:  info
  out_of_band_dtmf3:  abc
  rtp_dscp:  '46'
  rtp-dscp_1:  'EF'
  rtp_dscp_2:  '0'
  rtp_dscp_3:  '63'
  rtp_dscp_4:  '64'
  rtp_eth_qos:  '6'
  rtp_eth_qos_1:  '0'
  rtp_eth_qos_2:  '7'
  rtp_eth_qos_3:  '8'
  domain:  <not-set>
  domain_1:  'abcdefghijklmnopqrstuvwxyz.ABCDEFGHIGKLMNOPQRSTUWWXYZ1234567890'
  domain_2:  'a.cdefghijklmnopqrstuvwxyz.ABCDEFGHIGKLMNOPQRSTUWWXYZ1234567890'
  domain_3:  'abcdefghijklmnopqrstuvwxyz.ABCDEFGHIGKLMNOPQRSTUWWXYZ1234567890a'
  country_code:  '1'
  country_code_1:  '9000'
  country_code_2:  '10000'
  country_code_3:  '64'
  release_timer:  '10'
  release_timer_1:  '1'
  release_timer_2:  '21'
  rtp_port:  '49152'
  rtp_port_1:  '49154'
  rtp_port_2:  '65534'
  rtp_port_3:  '65536'
  switch_type:  none
  switch_type_zte:  zte 
  switch_type_huaw:  huaw
  switch_type_syla:  syla 
  switch_type_eric:  eric 
  switch_type_cs2k:  cs2k 
  switch_type_cs2000:  cs2000
  switch_type_bell:  bell
  switch_type_abc:  abc
  call_pickup_code:  ' '  
  call_pickup_code_1:  abc
  

  question_mark:  '\x03'
  user_number50:  12345678901234567890123456789012345678901234567890
  user_number50A:  AAA45678901234567890123456789012345678901234567890  
  password24:  123456789011234567891234
  password24A:  AAA456789011234567891234
  uri_number32: 12345678901234567890123456789012
  uri_number32A: AAA45678901234567890123456789012
  direct_connect:  <not-set>
  direct_connect1:  123456789012345
  direct_connect2:  0
  direct_connect_timer:  0
  direct_connect_timer1:  '1' 
  direct_connect_timer35:  '35' 
  direct_connect_timer36:  '36'
  dial_plan1:  system-default
  pots_holdover_timer:  '180'
  pots_holdover_timer0:  '0'
  pots_holdover_timer60:  '60'
  pots_holdover_timer59:  '59'
  pots_holdover_timer43200:  '43200'
  pots_holdover_timer65536:  '65536'
  rx_gain:  '-9.00'
  loss_plan_rx:  ansi
  tx_gain:  '-3.00'
  loss_plan_tx:  ansi
  loss_plan_rx_man:  'manual'
  loss_plan_tx_man:  'manual'
  manual_rx_gain:  '0.0'
  rx_gain_man:  '0.00'
  tx_gain_man:  '0.00'  
  manual_RX_gain12:  '-12'
  manual_TX_gain12:  '-12'
  manual_RX_gain120:  '-12.0'
  manual_TX_gain120:  '-12.0'
  manual_RX_gain6:  '6'
  manual_TX_gain6:  '6'
  manual_RX_gain60:  '6.0'
  manual_TX_gain60:  '6.0'
  manual_RX_gain_600:  '6.00'
  manual_TX_gain_600:  '6.00'
  manual_RX_gain122:  '12.2'
  manual_TX_gain122:  '12.2'
  manual_RX_gain622:  '6.2'
  manual_TX_gain622:  '6.2'
  gain_type_e:  etsi
  rx_gain_etsi:  '-11.00'
  tx_gain_etsi:  '-4.00'
  gain_type_a:  ansi
  rx_gain_ansi:  '-9.00'
  tx_gain_ansi:  '-3.00'
  gain_type_g:  gr909
  rx_gain_gr909:  '-4.00'
  tx_gain_gr909:  '-2.00'
  signaling_type:  loopstart
  signaling_type_ground:  groundstart
  description_1:  1234567890abcdefghijklmnopqrstuvwxyz.1234567890abcdefghijklmnopqrstuvwxyz.1234567890abcdefghijklmnopqrstuvwxyz.1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz
  description_2:  1234567890abcdefghijklmnopqrstuvwxyz.1234567890abcdefghijklmnopqrstuvwxyz.1234567890abcdefghijklmnopqrstuvwxyz.1234567890abcdefghijklmnopqrstuvwxyz.1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz
  class_map_name:  autol3-sip
  class_map_type1:  ethernet
  flow_type:  flow
  flow_index:  1
  rule_index:  1
  policy_map_name:  autol3-sip 
  sip_profile:  autosip-1   
  proxy_server:  10.245.252.2
  dial_plan:  autosip
  class_map_type2:  class-map-ethernet
  pattern1:  ^311
  pattern2:  ^201203[0-9]{4}
  ua_id:  1
  sip_profile_id:  autosip-1
  ont_ua_id:  auto838/1
  sip_service_number:  1
  uri_number1:  2012039886
  user_number1:  2012039886
  uri_number2:  2012039887 
  user_number2:  2012039887  
  password:  123456