connection:
  eutA:
    ip: 10.245.96.73
    user: sysadmin
    password: sysadmin
    type: AXOS
    model: MILAN
    protocol: ssh
    user_interface: CLI
    prompt: "#"
    timeout: 30
  eutB:
    ip: 10.245.96.71
    user: sysadmin
    password: sysadmin
    type: AXOS
    model: MILAN
    protocol: ssh
    user_interface: CLI
    prompt: "#"
    timeout: 30

  tg1:
    ip: 10.245.252.60
    type: stc
    protocol: stc
    ports:
      service_p1:         #connect to euta service
        port: 8/11
        medium: fiber
        speed: ether1000
      subscriber_p1:        #connect to eutb subscriber
        port: 11/13
        medium: fiber
        speed: ether10000