connection:
  eutA:
    ip: 10.245.96.74 
    user: sysadmin
    password: sysadmin
    type: AXOS
    model: MILAN
    protocol: ssh
    user_interface: CLI
    prompt: "#"
    timeout: 30
    shelf1:
      id: 1
      slot1:
        id: 1/2
        model: ngpon
        uplinkport1: 1/2/x3
        downlinkport1: 1/2/x4
        
  tg1:
    ip: 10.245.252.60
    type: stc
    protocol: stc
    ports:
      service_p1: 
        port: 12/3
        medium: fiber
        speed: ether10000
      subscriber_p1: 
        port: 3/5
        medium: fiber
        speed: ether10000