connection:
  eutA:
    ip: 10.245.96.72
    user: sysadmin
    password: sysadmin
    type: AXOS
    model: MILAN
    protocol: ssh
    user_interface: CLI
    prompt: "#"
    timeout: 30
    connect_timeout: 20

  tg1:
    ip: 10.245.252.60
    type: stc
    protocol: stc
    ports:
      service_p1:
        port: 11/4
        medium: fiber
        speed: ether10000
      subscriber_p1:
        port: 11/14
        medium: fiber
        speed: ether10000