global:
  service_model:
    # single node with subscriber
    service_point_list1:
       - service_point1
       - service_point2
       - service_point3
       - service_point4
    # uplink card 1 NGPON2-4
    service_point1:
      device: eutA
      type: eth                  # service_point type {eth|lag|g8032|erps}
      member:
        interface1: 1/1/x3
      attribute:
        interface_role: inni
    service_point2:
      device: eutA
      type: eth                  # service_point type {eth|lag|g8032|erps}
      member:
       interface1: 1/1/x4
      attribute:
        interface_role: inni
    # uplink card 2 10GE-12
    service_point3:
      device: eutA
      type: eth                  # service_point type {eth|lag|g8032|erps}
      member:
        interface1: 1/2/x11
      attribute:
        interface_role: inni
    service_point4:
      device: eutA
      type: eth                  # service_point type {eth|lag|g8032|erps}
      member:
        interface1: 1/2/x12
      attribute:
        interface_role: inni