connection:
  n1:
    ip: 10.245.96.72
    password: sysadmin
    user: sysadmin
    type: exa
    protocol: ssh
    ports:
      p1:
        port: 1/1/x1
        type: eth
      p2:
        port: 1/1/xp1
        type: pon
#  n1_sh:
#    ip: 10.206.9.1
#    password: root
#    user: root
#    type: exa
#    protocol: ssh
#  n1_console:
#    ip: 10.206.10.100
#    port: 10002
#    password: sysadmin
#    user: sysadmin
#    type: exa
#    protocol: telnet
#  n1_host:
#    ip: localhost
#    password: Test999___
#    user: llim
#    type: linux
#    protocol: ssh
  n1_auth:
    ip: 10.245.96.72
    password: authorized
    user: authorizeduser
    type: exa
    protocol: ssh
  n1_unauth:
    ip: 10.245.96.72
    password: unauthorized 
    user: unauthorizeduser 
    type: exa
    protocol: ssh

  tg1:
     ip: 10.245.252.60
     type: stc
     protocol: stc
     ports:
        p1:
         port: 11/4
         medium: fiber
         speed: ether10000
        p2:
         port: 11/14
         medium: fiber
         speed: ether10000

device_links:
  link1: {n1: p2, tg1: p1}
  link2: {n1: p5, tg1: p2}
