connection:
    n3:
        ip: 10.245.96.71
        user: sysadmin
        password: sysadmin
        type: AXOS
        model: MILAN
        prompt: "#"
        protocol: ssh
        timeout: 60
    n4:
        ip: 10.245.96.71
        user: root
        password: root
        type: linux
        model: MILAN
        prompt: root@NGPON2X4:~#
        protocol: ssh
        timeout: 30
