connection:
  eutA:
    ip: 10.245.96.72
    user: sysadmin
    password: sysadmin
    type: AXOS
    model: MILAN
    protocol: ssh
    user_interface: CLI
    prompt: "#"
    timeout: 30
  tg1:
    ip: 10.245.252.60
    type: stc
    protocol: stc
    ports:
      p1:                         # connect to service_point1
        port: 11/4
        medium: fiber
        speed: ether10000
      p2:                        # connect to service_point2
        port: 11/2
        medium: fiber
        speed: ether10000