connection:
  eutA:
    ip: 10.245.96.72
    user: sysadmin
    password: sysadmin
    type: AXOS
    model: MILAN
    protocol: ssh
    user_interface: CLI
    prompt: "#"
    timeout: 30

  tg1:
    ip: 10.245.252.60
    type: stc
    protocol: stc
    ports:
      service_p1:    # to the uplink
        port: 11/4
        medium: fiber
        speed: ether10000
      subscriber_p1: # to the subscriber point1
        port: 10/13    #12/7
        medium: copper
        speed: ether1000
      subscriber_p2: # to the subscriber point2&point3
        port: 11/14
        medium: fiber
        speed: ether10000
