global:
  service_model:
    service_point_list1:
      - service_point1
    service_point_list2:
      - service_point2
    service_point_list3:
      - service_point3
    service_point_list4:
      - service_point4
    service_point1:
      device: eutA
      type: lag
      name: la1
      member:
        interface1: 1/1/x2
      attribute:
        interface_role: lag
    service_point2:
      device: eutB
      type: lag
      name: la1
      member:
        interface1: 1/1/x2
      attribute:                             # all mandatory parameter should set to "" if you don't want to use it
        interface_role: lag
    service_point3:
      device: eutA
      type: lag
      name: la2
      member:
        interface1: 1/1/x3
      attribute:
        interface_role: lag
    service_point4:
      device: eutB
      type: lag
      name: la2
      member:
        interface1: 1/1/x3
      attribute:
        interface_role: lag
