global:
  service_model:
    service_point_list1:
      - service_point1
      - service_point2
      - service_point3
    service_point_list2:
      - service_point4

    # erps ring transit node with subscriber
    service_point_list3:
      - service_point3
      - service_point5
      - service_point6
    service_point1:
      device: eutA
      type: erps
      name: 6
      member:
        interface1: 1/1/x1
        interface2: 1/1/g1
      attribute:                 # all mandatory parameter should set to "" if you don't want to use it
        interface_role: inni
        interface_type: ethernet
        control_vlan: 10
        erps_role: master             # ring domain node role {master|transit}
        interface1_erps_role: primary
        interface2_erps_role: secondary
    service_point2:
      device: eutB
      type: erps
      name: 6
      member:
        interface1: 1/1/x2
        interface2: 1/1/x3
      attribute:                 # all mandatory parameter should set to "" if you don't want to use it
        interface_role: inni
        interface_type: ethernet
        control_vlan: 10
        erps_role: transit             # ring domain node role {master|transit}
        interface1_erps_role: primary
        interface2_erps_role: secondary
    service_point3:
      device: eutC
      type: erps
      name: 6
      member:
        interface1: 1/1/x2
        interface2: 1/1/g2
      attribute:                 # all mandatory parameter should set to "" if you don't want to use it
        interface_role: inni
        interface_type: ethernet
        control_vlan: 10
        erps_role: transit             # ring domain node role {master|transit}
        interface1_erps_role: primary
        interface2_erps_role: secondary

    service_point4:
      device: eutB
      type: eth
      member:
        interface1: 1/1/x4
      attribute:
        interface_role: inni
        interface_type: ethernet
    
    service_point5:
      device: eutA
      type: erps
      name: 6
      member:
        interface1: 1/1/x1
        interface2: 1/1/g1
      attribute:                 # all mandatory parameter should set to "" if you don't want to use it
        interface_role: inni
        interface_type: ethernet
        control_vlan: 10
        erps_role: transit             # ring domain node role {master|transit}
        interface1_erps_role: primary
        interface2_erps_role: secondary
    service_point6:
      device: eutB
      type: erps
      name: 6
      member:
        interface1: 1/1/x2
        interface2: 1/1/x3
      attribute:                 # all mandatory parameter should set to "" if you don't want to use it
        interface_role: inni
        interface_type: ethernet
        control_vlan: 10
        erps_role: master             # ring domain node role {master|transit}
        interface1_erps_role: primary
        interface2_erps_role: secondary

    subscriber_point3:
      device: eutA
      type: ont_port             # subscriber port type {ont_port|dsl|dsl_bond|eth}
      name: 1/x1
      member:
        interface1: 1/x1
      attribute:                 # all mandatory parameter should set to "" if you don't want to use it
        interface_role: uni
        interface_type: ont-ethernet
        ont_id: 1
        ont_profile_id: 811NG     # use ont-profile on cli
        serial_number: 384AE2
        vendor_id: CXNK
        pon_port:
          - 1/1/xp1

    subscriber_point2:
      device: eutA
      type: ont_port             # subscriber port type {ont_port|dsl|dsl_bond|eth}
      name: 2/x1
      member:
        interface1: 2/x1
      attribute:                 # all mandatory parameter should set to "" if you don't want to use it
        interface_role: uni
        ont_id: 2
        ont_profile_id: 801XGS     # use ont-profile on cli
        serial_number: 3D15B5
        vendor_id: CXNK
        pon_port:
          - 1/1/xp1
    subscriber_point1:
      device: eutC
      type: ont_port             # subscriber port type {ont_port|dsl|dsl_bond|eth}
      name: 854/g1
      member:
        interface1: 854/g1
      attribute:                 # all mandatory parameter should set to "" if you don't want to use it
        interface_role: uni
        interface_type: ont-ethernet
        ont_id: 854
        ont_profile_id: 844G_ARF     # use ont-profile on cli
        serial_number: 1D1D43
        vendor_id: CXNK
        pon_port:
          - 1/1/gp1
          