connection:
  eutA:
    ip: 10.245.74.72
    user: sysadmin
    password: sysadmin
    type: AXOS
    model: MILAN
    protocol: ssh
    user_interface: CLI
    prompt: "#"
    timeout: 30
    
  ontA:
    ip: 10.245.96.10
    port: 10027
    type: ont
    login_prompt: '> '
    password_prompt: '> '
    protocol: telnet
    prompt: [' > ',' # ','HELO']
    timeout: '5' 
    