connection:
  eutA:
    ip: 10.245.96.76
    user: sysadmin
    password: sysadmin
    type: AXOS
    model: MILAN
    protocol: ssh
    user_interface: CLI
    prompt: "#"
    timeout: 30
  eutB:
    ip: 10.245.96.74
    user: sysadmin
    password: sysadmin
    type: AXOS
    model: MILAN
    protocol: ssh
    user_interface: CLI
    prompt: "#"
    timeout: 30
  eutC:
    ip: 10.245.96.75
    user: sysadmin
    password: sysadmin
    type: AXOS
    model: MILAN
    protocol: ssh
    user_interface: CLI
    prompt: "#"
    timeout: 30

  tg1:
    ip: 10.245.252.60
    type: stc
    protocol: stc
    ports:
      service_p1:
        port: 10/7
        medium: fiber
        speed: ether1000
      subscriber_p1:
        port: 10/8
        medium: fiber
        speed: ether1000