connection:

  eutA:
    ip: 10.245.74.73
    user: sysadmin
    password: sysadmin
    type: AXOS
    model: MILAN
    protocol: ssh
    user_interface: CLI
    prompt: "#"
    timeout: 30
  eutA_root:
    ip: 10.245.74.73
    user: root
    password: root
    type: AXOS
    model: MILAN
    protocol: ssh
    user_interface: CLI
    prompt: "~#"
    timeout: 30
  tg1:
    ip: 10.245.252.60
    type: stc
    protocol: stc
    ports:
      p1:
        port: 11/11
        medium: fiber
        speed: ether10000
      p2:
        port: 10/12
        medium: copper
        speed: ether1000
       