global:

# dhcp parameters
  server_ip:    10.10.10.1
  pool_ip_start:   10.10.10.10
  server_mac:    aa:bb:cc:00:00:00
  client_mac:    00:00:00:aa:bb:cc
  sip:           20.20.20.2
  dip:           20.20.20.20
  smac:          00:00:00:11:22:33
  dmac:          00:00:00:44:55:66
  lease_negociate_time:    60
  rate_pps:     10000
  lost_rate:     0.001
  traffic_run_time:    10s
  ERPS_max_second_for_switch:    0.2
  send_traffic_time:    10s
  stop_traffic_time:    10s

# pppoe parameter
  pppoe_negotiated_time: 40
  id_profile_name: pppoe1
  rate_kbps: 50

  health_time_default: "5"
  recovery_time_default: "1"
  service_vlan: 777
  subscriber_vlan: 3001
  dhcp_profile_name: dhcp_profile

#  ccm parameter:
  meg1:    meg1
  mep1:    100
  meg2:    meg2
  mep2:    300
  meg3:    meg1
  mep3:    200
  meg4:    meg2
  mep4:    400

