connection:
  eutA:
    ip: 10.245.74.72
    user: sysadmin
    password: sysadmin
    type: AXOS
    model: GPON8r2
    protocol: ssh
    user_interface: CLI
    prompt: "#"
    timeout: 30
       
  tg1:
    ip: 10.245.252.60
    type: stc
    protocol: stc
    ports:
      p2:
        port: 11/5
        medium: fiber
        speed: ether10000
      p1:
        port: 11/6
        medium: fiber
        speed: ether10000