connection:
  eutA:
    ip: 10.245.96.73
    user: sysadmin
    password: sysadmin
    type: AXOS
    model: MILAN
    protocol: ssh
    user_interface: CLI
    prompt: "#"
    timeout: 30
       
  tg1:
    ip: 10.245.252.60
    type: stc
    protocol: stc
    ports:
      p1:
        port: 11/13
        medium: fiber
        speed: ether10000
      p2:
        port: 11/3
        medium: fiber
        speed: ether10000