connection:

  n1_console:
    ip: 10.245.96.10
    port: 10008
    type: exa
    protocol: telnet
    user: sysadmin
    password: sysadmin
    device_type: exa
    login_prompt: 'login:'
    password_prompt: 'Password:'
    prompt: ['#']
    timeout: 300

  eutA:
    ip: 10.245.96.71
    user: sysadmin
    password: sysadmin
    type: AXOS
    model: MILAN
    protocol: ssh
    user_interface: CLI
    prompt: "#"
    timeout: 30


  eutB:
    ip: 10.245.96.77
    user: sysadmin
    password: sysadmin
    type: AXOS
    model: MILAN
    protocol: ssh
    user_interface: CLI
    prompt: "#"
    timeout: 30




