global:
  service_model:
    service_point_list1:
      - service_point1
    service_point1:
      device: eutA
      type: eth
      member:
        interface1: 1/1/x3
      attribute:
        interface_role: inni

    subscriber_point1: 
      device: eutA
      type: ont_port             # subscriber port type {ont_port|dsl|dsl_bond|eth}
      name: 102/g3
      member:
        interface1: 102/g3
      attribute:                 # all mandatory parameter should set to "" if you don't want to use it
        interface_role: uni
        interface_type: ont-ethernet
        ont_id: 102
        ont_profile_id: 854G_ARF       # use ont-profile on cli
        serial_number: 2D5640
        vendor_id: CXNK
        pon_port:
          - 1/1/gp1

    subscriber_point2:
      device: eutA
      type: ont_port             # subscriber port type {ont_port|dsl|dsl_bond|eth}
      name: 100/g2
      member:
        interface1: 100/g2
      attribute:                 # all mandatory parameter should set to "" if you don't want to use it
        interface_role: uni
        interface_type: ont-ethernet
        ont_id: 100
        ont_profile_id: 836GE_ARF       # use ont-profile on cli
        serial_number: 1325BB
        vendor_id: CXNK
        pon_port:       # use list for FFP
          - 1/1/gp1

    subscriber_point3:
      device: eutA
      type: ont_port             # subscriber port type {ont_port|dsl|dsl_bond|eth}
      name: 101/g2
      member:
        interface1: 101/g2
      attribute:                 # all mandatory parameter should set to "" if you don't want to use it
        interface_role: uni
        interface_type: ont-ethernet
        ont_id: 101
        ont_profile_id: 844G_ARF       # use ont-profile on cli
        serial_number: 3E4020
        vendor_id: CXNK
        pon_port:       # use list for FFP
          - 1/1/gp8